# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a5663840d094ff5e57428489b2d63ecee0af21743b62fbd50343f60a1d48f2cb16cf469d1c34e1fd2adeb03f8fe4eca045a03cc32a706d15d05ef3443f1706

test:
  secret_key_base: 83b980199049bbe7192eb50698d079c4f0c0681c1d99504cac5c4e60711153be53fac7d60ac8d285feacfd0f929b830046094f30a66d6c42866015d8943e95d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
